import './globals.css'
import Layout from '@/components/Layout'
import Modal from '@/components/Modal'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
        <Modal isOpen />
      </body>
    </html>
  )
}
